feat: Add bxArrowIcons
homebound-team/beam pull request #696
Opened 2022-10-21 21:46 UTC by asanchezHB

- Add bxArrowIcons
<img width="62" alt="image" src="https://user-images.githubusercontent.com/97992415/197293238-292a5c3c-a320-47ff-8395-c6bbb0a98e19.png">

[Figma reference](https://www.figma.com/file/gxrfuWnQA9RnfjMGk7tX4W/22-Q3-%F0%9F%9B%A0-Lot-Config-%2F-Sequence-Sheet?node-id=3900%3A24769)

[Related ticket](https://app.shortcut.com/homebound-team/story/23020/ui-move-project-from-one-development-to-another)

2022-10-22 16:29 UTC, stephenh approved these changes

2022-10-24 13:35 UTC, bdow commented on src/components/Icon.stories.tsx
> +    "bxArrowFromTop",
(giving the same suggestion here)
```suggestion
    "arrowFromBottom",
    "arrowFromLeft",
    "arrowFromRight",
    "arrowFromTop",
```

2022-10-24 13:38 UTC, bdow requested changes
It appears these icons are not lined up properly inside of their 24x24 bounding box. See the attached screenshot. For more details on properly adding icons to Beam see: https://homebound.atlassian.net/wiki/spaces/BEAM/pages/2518679559/Adding+an+Icon
<img width="215" alt="Screen Shot 2022-10-24 at 9 36 38 AM" src="https://user-images.githubusercontent.com/1143861/197539131-be55f25e-ccb2-4a27-98d5-b8d43586bfd9.png">

2022-10-24 16:57 UTC, bdow approved these changes
Thanks for updating!

2022-10-24 17:52 UTC, merged